openapiOptions:
  file:
    - file: "pb/ordering.api.proto"
      option:
        info:
          title: Order Processing
          version: "1.0.0"
        basePath: /
  method:
    - method: pb.OrderingService.CreateOrder
      option:
        operationId: createOrder
        tags:
          - Order
        summary: Start a new order
    - method: pb.OrderingService.GetOrder
      option:
        operationId: getOrder
        tags:
          - Order
        summary: Get an order
    - method: pb.OrderingService.CancelOrder
      option:
        operationId: cancelOrder
        tags:
          - Order
        summary: Cancel an order
